### ISSUE TITLE
[Verify]: Game Name

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex-Backend#3]
### Extension URL

123

### Game URL

456

### Confirmation

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested

### 🖱️Tasks

```[tasklist]
## (What do engineers have to do step by step?)
- [ ] Verify the issue
- [ ] Solve the issue
- [ ] Test the solution
````
