### ISSUE TITLE
[Verify]: Game Name

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex-Backend#4]
### Extension URL

https://www.nexusmods.com/site/mods/770

### Game URL

https://www.nexusmods.com/palworld

### Confirmation

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested

### 🖱️Tasks

```[tasklist]
## (What do engineers have to do step by step?)
- [ ] Verify the issue
- [ ] Solve the issue
- [ ] Test the solution
```
